name: cs236756
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - torchvision=0.4.1
  - pillow<7.0 # version 7 breaks torchvision 0.4.2 and earlier
  - ipython>=7.9
  - numpy
  - scikit-learn
  - jupyterlab
  - matplotlib
  - jupyter
  - pandas
  - pip
